POST http://localhost:3000/subscribe
Content-Type: application/json

{
  "topic": "test_1",
  "subscriber": "alpha"
}

###

POST http://localhost:3000/publish
Content-Type: application/json

{
  "topic": "test_1",
  "data": {
    "txKind": "withdrawal",
    "currencyShortName": "eth",
    "txHash": "2a1cb01c08ab64915727e9e1a902fc68b6d07a0518507b7715ff620fce90aa6",
    "valueInCrypto": "0.00094280",
    "valueInTether": "9.10694280",
    "createdAt": 1585137738,
    "updatedAt": 1585137738,
    "confirmations": 1,
    "maxConfirmations": 6,
    "status": "success",
    "totalFee": "0.00000168",
    "to": "2NBWXaMZY8wLGUMpBKJQQdAeHFCsMifBC2K"
  }
}

###


GET http://localhost:3000/poll?topic=test_1&subscriber=alpha
Content-Type: application/json


###


POST http://localhost:3000/unsubscribe
Content-Type: application/json

{
  "topic": "test_1",
  "subscriber": "alpha"
}
